=== sambec/EncodingGiry/LettersEncoding/EncodedLetters.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT ns1:TEI (ns1:teiHeader,ns1:text)>
<!ATTLIST ns1:TEI
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:teiHeader (ns1:fileDesc,ns1:encodingDesc,ns1:profileDesc)>
<!ATTLIST ns1:teiHeader
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:text (ns1:body)>
<!ATTLIST ns1:text
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:fileDesc (ns1:titleStmt,ns1:publicationStmt,
                        ns1:sourceDesc)>
<!ATTLIST ns1:fileDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:encodingDesc (ns1:p)>
<!ATTLIST ns1:encodingDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:profileDesc (ns1:correspDesc)>
<!ATTLIST ns1:profileDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:body (ns1:head,ns1:opener,ns1:p+,ns1:closer,
                    ns1:postscript)>
<!ATTLIST ns1:body
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:titleStmt (ns1:title)>
<!ATTLIST ns1:titleStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:publicationStmt (ns1:distributor,ns1:date,
                               ns1:availability)>
<!ATTLIST ns1:publicationStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:sourceDesc (ns1:msDesc)>
<!ATTLIST ns1:sourceDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:correspDesc (ns1:correspAction)+>
<!ATTLIST ns1:correspDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:head (#PCDATA)>
<!ATTLIST ns1:head
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:opener (ns1:dateline,ns1:salute)>
<!ATTLIST ns1:opener
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:closer (ns1:salute,ns1:signed)>
<!ATTLIST ns1:closer
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:postscript (ns1:p)+>
<!ATTLIST ns1:postscript
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:distributor (#PCDATA)>
<!ATTLIST ns1:distributor
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:availability (ns1:licence)>
<!ATTLIST ns1:availability
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:msDesc (ns1:msIdentifier)>
<!ATTLIST ns1:msDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:correspAction (ns1:persName,ns1:placeName,ns1:date?)>
<!ATTLIST ns1:correspAction
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:dateline (#PCDATA|ns1:placeName)*>
<!ATTLIST ns1:dateline
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:signed (#PCDATA)>
<!ATTLIST ns1:signed
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:licence (#PCDATA|ns1:ref)*>
<!ATTLIST ns1:licence
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:msIdentifier (ns1:settlement,ns1:institution,ns1:idno)>
<!ATTLIST ns1:msIdentifier
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:ref (#PCDATA)>
<!ATTLIST ns1:ref
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  target CDATA #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:settlement (#PCDATA)>
<!ATTLIST ns1:settlement
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:institution (#PCDATA)>
<!ATTLIST ns1:institution
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:idno (#PCDATA)>
<!ATTLIST ns1:idno
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:title (#PCDATA)>
<!ATTLIST ns1:title
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:date (#PCDATA)>
<!ATTLIST ns1:date
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  when NMTOKEN #IMPLIED>

<!ELEMENT ns1:p (#PCDATA|ns1:date|ns1:persName|ns1:title|ns1:orgName)*>
<!ATTLIST ns1:p
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:orgName (#PCDATA)>
<!ATTLIST ns1:orgName
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ref CDATA #REQUIRED>

<!ELEMENT ns1:persName (#PCDATA)>
<!ATTLIST ns1:persName
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:placeName (#PCDATA)>
<!ATTLIST ns1:placeName
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:salute (#PCDATA)>
<!ATTLIST ns1:salute
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

=== sambec/EncodingGiry/LettersEncoding/leon_dorez.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!DOCTYPE TEI SYSTEM "EncodedLetters.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Lettre de Léon Dorez à Arthur Giry concernant la constitution du Manuel de
                    Diplomatique (1894)</title>
            </titleStmt>
            <publicationStmt>
                <distributor>Sarah Ambec</distributor>
                <date>Octobre 2024</date>
                <availability>
                    <licence>This file is available under a Creative Commons Attribution 4.0
                        licence: <ref type="url"
                            target="https://creativecommons.org/licenses/by/4.0/deed.en"
                            >https://creativecommons.org/licenses/by/4.0/deed.en</ref>. </licence>
                </availability>
            </publicationStmt>
            <sourceDesc>
                <msDesc>
                    <msIdentifier>
                        <settlement>Paris</settlement>
                        <institution>Archives Nationales</institution>
                        <idno>93AJ/264</idno>
                    </msIdentifier>
                </msDesc>
            </sourceDesc>
        </fileDesc>

        <encodingDesc>
            <p>This transcription was created by <persName>Sarah Ambec</persName> in
                    <date>2019</date> for her master’s thesis, a biography of <persName>Arthur
                    Giry</persName>, written at <orgName ref="https://www.sorbonne-universite.fr/"
                    >Sorbonne University</orgName>, Paris. The letters have now been encoded in XML
                in <date>2024</date> as part of a digital humanities project at <orgName
                    ref="https://www.chartes.psl.eu/">École nationale des chartes -
                PSL</orgName>.</p>
        </encodingDesc>

        <profileDesc>
            <correspDesc>
                <correspAction type="sent">
                    <persName>Léon Dorez</persName>
                    <placeName>Rome</placeName>
                    <date when="1891-12-25"/>
                </correspAction>
                <correspAction type="received">
                    <persName>Arthur Giry</persName>
                    <placeName>Paris</placeName>
                </correspAction>
            </correspDesc>
        </profileDesc>

    </teiHeader>
    <text>
        <body>
            <opener>
                <dateline><placeName>Rome</placeName>, le 25 décembre 1891</dateline>
                <salute>Cher Monsieur,</salute>
            </opener>

            <p>Je vous remercie beaucoup du renseignement que vous m’envoyez, bien qu’il soit
                négatif, comme je m’y attendais.</p>

            <p>Quant à celui que vous ai expédié un peu au hasard, je suis heureux qu’il vous ait
                évité une recherche de plus. La statue de St Hyppolyte, découverte en 1551, doit
                être au Latran depuis ce temps, ou à peu près; en tout cas, elle y est aujourd’hui.
                Paul Allard, <title>Les Dernières persécutions du troisième siècle</title>, Paris,
                Lecoffre, 1887, in 8° p.93 n°3 renvoi aux principaux articles bibliographiques,
                entre autres aux observations de de Rossi dans son <title>Bulletin</title>, 1881,
                p.29 en 1882, PP.42-43, ainsi qu’à Raus. Le mieux, dans un livre comme le vôtre,
                serait, je crois, de renvoyer à ce dernier auteur qui donne dans sa
                    <title>Real-Encyclopädie der christkichen Altchümer</title>, Fribourg en
                Brisgau, 1882, 8°-, t.I, p.660-664, une sorte de facsimilé de l’inscriptions
                accompagné d’une transcription et d’un dessin représentant la statue.</p>

            <p>Heureux d’être entré en relations épistolaires avec vous, j’espère que vous voudrez
                bien nous adresser à moi en toute autre circonstance analogue à celle-ci, et je vous
                prie d’agréer, pour vous et votre famille, les meilleurs vœux de nouvelle année
                de</p>

            <closer>
                <salute>Votre élève dévoué,</salute>
                <signed>Léon Dorez</signed>
            </closer>
        </body>
    </text>
</TEI>

=== sambec/EncodingGiry/LettersEncoding/theophile_dufour.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!DOCTYPE TEI SYSTEM "EncodedLetters.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Lettre de Théophile Dufour à Arthur Giry concernant la constitution du Manuel
                    de Diplomatique (1894)</title>
            </titleStmt>
            <publicationStmt>
                <distributor>Sarah Ambec</distributor>
                <date>Octobre 2024</date>
                <availability>
                    <licence>This file is available under a Creative Commons Attribution 4.0
                        licence: <ref type="url"
                            target="https://creativecommons.org/licenses/by/4.0/deed.en"
                            >https://creativecommons.org/licenses/by/4.0/deed.en</ref>. </licence>
                </availability>
            </publicationStmt>
            <sourceDesc>
                <msDesc>
                    <msIdentifier>
                        <settlement>Paris</settlement>
                        <institution>Archives Nationales</institution>
                        <idno>93AJ/264</idno>
                    </msIdentifier>
                </msDesc>
            </sourceDesc>
        </fileDesc>

        <encodingDesc>
            <p>This transcription was created by <persName>Sarah Ambec</persName> in
                    <date>2019</date> for her master’s thesis, a biography of <persName>Arthur
                    Giry</persName>, written at <orgName ref="https://www.sorbonne-universite.fr/"
                    >Sorbonne University</orgName>, Paris. The letters have now been encoded in XML
                in <date>2024</date> as part of a digital humanities project at <orgName
                    ref="https://www.chartes.psl.eu/">École nationale des chartes -
                PSL</orgName>.</p>
        </encodingDesc>

        <profileDesc>
            <correspDesc>
                <correspAction type="sent">
                    <persName>Théophile Dufour</persName>
                    <placeName>Genève</placeName>
                    <date when="1890-11-14"/>
                </correspAction>
                <correspAction type="received">
                    <persName>Arthur Giry</persName>
                    <placeName>Paris</placeName>
                </correspAction>
            </correspDesc>
        </profileDesc>

    </teiHeader>



    <text>
        <body>
            <head> Papier à lettre de la Bibliothèque publique de Genève </head>
            <opener>
                <dateline><placeName>Genève</placeName>, le 14 novembre 1890</dateline>
                <salute>Mon cher confrère et ami,</salute>
            </opener>

            <p>Veuillez m’excuser de n’avoir pas encore répondu à votre demande. Pendant les trois
                semaines qui viennent de s’écouler, le peu de loisir que me laisse la Bibliothèque a
                été absorbé par des Comités électoraux qui tenaient séance tous les jours. Aussi
                ai-je maintenant une série de lettres en retard.</p>

            <p>Mon exemplaire personnel de l’<title>Indicateur d’histoire</title> nuse étant encore
                bâclé, je vous envoie la partie du n°3 de 1886 où se trouve le petit article de
                Monseigneur Brandstetter que vous désirez. Vous verrez, dès les premiers mots, qu’il
                se réfère à un mémoire plus étendu publié par lui dans le tome 25 du
                    <title>Geschiches feund</title>, qui est l’organe de la vocicore d’honneur des
                cieux cantons de Lucernes Uni, Schuzz, Vutenvalden et ZplaceNameug. Ce mémoire, qui
                date de 1870 et qui comprend 41 pages est intitulé <title>Kurze Anleitung zum
                    Vebensehzen der Dahen, mit besonderer Rücksicht auf schweizeriche
                    Urkunden</title>. Si vous ne trouvez pas à Paris la collection du
                    <title>Geichichtefeund</title>, je suis prêt à vous envoyer ce tome 25 en
                communication.</p>

            <p>En ce qui concerne l’ancien diocèse de Genève, et plus tard la République de Genève,
                la question des styles est des plus simples : jusqu’en 1306, style pascal; - de 1306
                à 1575, style natal. Voir <title>Régeste genevois</title>, n°1565 (l’ouvrage se
                trouve à la Bibliothèque de l’Ecole des Chartes). En 1701, introduction du
                calendrier grégorien : Voir [...] de la Société de l’histoire de Genève, t.XXII,
                p.348-357 (même observation).</p>

            <p>Pour les autres cantons, je ne suis pas en mesure de vous donner des renseignements
                aussi certains. Mais, si vous le désirez, il me sera très facile d’écrire à ce sujet
                à quelques amis de Zurich, Berne, Bâle, Fribourg et Lausanne. Je crois que, de cette
                façon, vous auriez du nouveau et du solide, tandis que les Manuels ne font guère,
                d’habitude, que se copier les uns les autres. Usez librement de moi, je serai très
                heureux d’être toujours à votre disposition.</p>

            <closer>
                <salute>Veuillez me rappeler au souvenir de Madame Giry et me croire, je vous prie,
                    votre bien dévoué.</salute>
                <signed>Th Dufour</signed>
            </closer>

            <postscript>
                <p>L’an dernier, je suis allé trois fois à Paris, sans avoir pu, malheureusement,
                    aller vous faire une visite. Il est vrai que, la seconde fois, je demeurais à la
                    campagne, près de Meudon, que la troisième, j’ai pris l’influenza et que la
                    première a été absorbée par l’Exposition et par le mariage d’un de mes parents.
                    Cette année, je me suis reposé! Ce long voyage que j’ai fait si souvent,
                    commence à me fatiguer beaucoup.</p>
                <p>Prière de ne pas égarer les quelques pages de l’<title>Augriger</title> que je
                    vous envoie. C’est une collection très difficile à compléter en cas de perte
                    d’un numéro.</p>
            </postscript>
        </body>
    </text>
</TEI>
